import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About',
  description: 'Learn how Is It Worth It? works and our affiliate disclosure.',
};

export default function AboutPage() {
  return (
    <main className="mx-auto flex max-w-3xl flex-col gap-12 px-4 py-12">
      <div>
        <h1 className="text-3xl font-bold text-zinc-900 dark:text-zinc-50">
          About Is It Worth It?
        </h1>
        <p className="mt-3 text-zinc-500 dark:text-zinc-400">
          AI-powered furniture value comparisons to help you make smarter buying decisions.
        </p>
      </div>

      <section id="how-it-works" className="flex flex-col gap-4">
        <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">How It Works</h2>
        <ol className="flex flex-col gap-3">
          {[
            ['Paste a URL or describe a product', 'Submit any furniture product URL from major retailers, or describe what you\'re looking for in plain text.'],
            ['AI identifies the product', 'Our system uses GPT-4 to extract product details — name, price, materials, dimensions, and style characteristics.'],
            ['We find similar alternatives', 'Using vector embeddings, we search our database for furniture with similar attributes at different price points.'],
            ['Get an honest value score', 'GPT-4 compares the source product against alternatives and generates a value score (1–100), verdict, and comparison notes.'],
          ].map(([title, desc], i) => (
            <li key={i} className="flex gap-4">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-zinc-900 text-xs font-bold text-white dark:bg-zinc-100 dark:text-zinc-900">
                {i + 1}
              </span>
              <div>
                <p className="font-medium text-zinc-900 dark:text-zinc-50">{title}</p>
                <p className="mt-0.5 text-sm text-zinc-500 dark:text-zinc-400">{desc}</p>
              </div>
            </li>
          ))}
        </ol>
      </section>

      <section id="affiliate-disclosure" className="flex flex-col gap-4">
        <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">Affiliate Disclosure</h2>
        <div className="rounded-2xl border border-zinc-100 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900">
          <p className="leading-relaxed text-zinc-600 dark:text-zinc-400">
            Some links on this site are affiliate links. When you click one and make a purchase, we
            may earn a small commission at no extra cost to you. This helps keep the service free.
          </p>
          <p className="mt-3 leading-relaxed text-zinc-600 dark:text-zinc-400">
            Our recommendations are generated by AI based on product similarity and value metrics —
            not by affiliate commission rates. We link to the same products regardless of whether
            they have affiliate programs.
          </p>
          <p className="mt-3 text-sm text-zinc-400 dark:text-zinc-500">
            This disclosure complies with the FTC&apos;s guidelines concerning the use of endorsements
            and testimonials in advertising.
          </p>
        </div>
      </section>

      <section id="privacy" className="flex flex-col gap-4">
        <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50">Privacy</h2>
        <p className="leading-relaxed text-zinc-600 dark:text-zinc-400">
          When you click an affiliate link, we log the click event with a hashed (SHA-256) version
          of your IP address for fraud prevention. We never store raw IP addresses. No personal
          account is required to use this service.
        </p>
      </section>
    </main>
  );
}
