import { Retailer } from '@/lib/types';

export const SEED_RETAILERS: Omit<Retailer, 'id'>[] = [
  {
    name: 'Wayfair',
    slug: 'wayfair',
    affiliate_network: 'cj',
    commission_rate: 0.07,
    cookie_days: 7,
    feed_url: null,
    feed_format: 'csv',
    logo_url: null,
    is_active: true,
  },
  {
    name: 'AllModern',
    slug: 'allmodern',
    affiliate_network: 'cj',
    commission_rate: 0.07,
    cookie_days: 7,
    feed_url: null,
    feed_format: 'csv',
    logo_url: null,
    is_active: true,
  },
  {
    name: 'West Elm',
    slug: 'west-elm',
    affiliate_network: 'rakuten',
    commission_rate: 0.05,
    cookie_days: 14,
    feed_url: null,
    feed_format: 'xml',
    logo_url: null,
    is_active: true,
  },
  {
    name: 'Article',
    slug: 'article',
    affiliate_network: 'shareasale',
    commission_rate: 0.08,
    cookie_days: 30,
    feed_url: null,
    feed_format: 'csv',
    logo_url: null,
    is_active: true,
  },
  {
    name: 'Crate & Barrel',
    slug: 'crate-barrel',
    affiliate_network: 'cj',
    commission_rate: 0.06,
    cookie_days: 14,
    feed_url: null,
    feed_format: 'csv',
    logo_url: null,
    is_active: true,
  },
];
